# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: postgresql
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - ./volumes/n8n_data:/root/.n8n
    networks:
      - n8n_network
    depends_on:
      - db
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11435:11435"
    environment:
      - OLLAMA_GPU_LAYERS=20
      - OLLAMA_NUM_PARALLEL=4
    volumes:
      - ./volumes/ollama_data:/root/.ollama
    networks:
      - n8n_network

networks:
  n8n_network:
